# Generated by Django 4.0.2 on 2022-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoqueitens_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='valor_da_entrada',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Valor_da_entrada'),
            preserve_default=False,
        ),
    ]
